#! /bin/bash
case $1 in
    pre)
        declare -a devices=(GPP0 GPP8 GP17 XHC0 GP18 GPP2 AS42 I211) # <-- Add your entries here

        for device in "${devices[@]}"; do
            if $(grep -qw ^${device}.*enabled /proc/acpi/wakeup); then
                echo ${device} > /proc/acpi/wakeup
            fi
        done
    ;;
esac
